/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@offertrail/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildConsentsDomainModule,
  buildFulfilmentsDomainModule,
  buildIdentityDomainModule,
  buildIncidentsDomainModule,
  buildJourneysDomainModule,
  buildOffersDomainModule,
  buildReportingDomainModule,
} from "../domains/index.js";
import type {
  ConsentsDomainModule,
  FulfilmentsDomainModule,
  IdentityDomainModule,
  IncidentsDomainModule,
  JourneysDomainModule,
  OffersDomainModule,
  ReportingDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private consentsModule: ConsentsDomainModule | null = null;
  private fulfilmentsModule: FulfilmentsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private incidentsModule: IncidentsDomainModule | null = null;
  private journeysModule: JourneysDomainModule | null = null;
  private offersModule: OffersDomainModule | null = null;
  private reportingModule: ReportingDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get consents domain module
   */
  getConsentsDependencies(): ConsentsDomainModule {
    if (!this.consentsModule) {
      this.consentsModule = buildConsentsDomainModule(this.dynamoClient);
    }
    return this.consentsModule;
  }

  /**
   * Get fulfilments domain module
   */
  getFulfilmentsDependencies(): FulfilmentsDomainModule {
    if (!this.fulfilmentsModule) {
      this.fulfilmentsModule = buildFulfilmentsDomainModule(this.dynamoClient);
    }
    return this.fulfilmentsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get incidents domain module
   */
  getIncidentsDependencies(): IncidentsDomainModule {
    if (!this.incidentsModule) {
      this.incidentsModule = buildIncidentsDomainModule(this.dynamoClient);
    }
    return this.incidentsModule;
  }

  /**
   * Get journeys domain module
   */
  getJourneysDependencies(): JourneysDomainModule {
    if (!this.journeysModule) {
      this.journeysModule = buildJourneysDomainModule(this.dynamoClient);
    }
    return this.journeysModule;
  }

  /**
   * Get offers domain module
   */
  getOffersDependencies(): OffersDomainModule {
    if (!this.offersModule) {
      this.offersModule = buildOffersDomainModule(this.dynamoClient);
    }
    return this.offersModule;
  }

  /**
   * Get reporting domain module
   */
  getReportingDependencies(): ReportingDomainModule {
    if (!this.reportingModule) {
      this.reportingModule = buildReportingDomainModule(this.dynamoClient);
    }
    return this.reportingModule;
  }

  clearConsentsDependencies(): void { this.consentsModule = null; }
  clearFulfilmentsDependencies(): void { this.fulfilmentsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearIncidentsDependencies(): void { this.incidentsModule = null; }
  clearJourneysDependencies(): void { this.journeysModule = null; }
  clearOffersDependencies(): void { this.offersModule = null; }
  clearReportingDependencies(): void { this.reportingModule = null; }

  getConsentsDependenciesForRequest(): ConsentsDomainModule {
    return this.getConsentsDependencies();
  }

  getFulfilmentsDependenciesForRequest(): FulfilmentsDomainModule {
    return this.getFulfilmentsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getIncidentsDependenciesForRequest(): IncidentsDomainModule {
    return this.getIncidentsDependencies();
  }

  getJourneysDependenciesForRequest(): JourneysDomainModule {
    return this.getJourneysDependencies();
  }

  getOffersDependenciesForRequest(): OffersDomainModule {
    return this.getOffersDependencies();
  }

  getReportingDependenciesForRequest(): ReportingDomainModule {
    return this.getReportingDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.consentsModule = null;
    this.fulfilmentsModule = null;
    this.identityModule = null;
    this.incidentsModule = null;
    this.journeysModule = null;
    this.offersModule = null;
    this.reportingModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
