/**
 * Handlers for JourneyCompare
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { CompareJourneysInput } from "@offertrail/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reports/journey-compare
 * Operation: compareJourneys
 */
export async function compareJourneys(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CompareJourneysInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.journeyCompares.get.execute(input);
  return reply.code(200).send(result);
}


