/**
 * Consents Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const grantConsent_Body = z
  .object({
    offerId: z.string().regex(/^ofr_[0-9A-HJKMNP-TV-Z]{26}$/),
    subjectRef: z.string().min(1),
    channel: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  grantConsent_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/consents',
    alias: 'listConsents',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'offerId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^ofr_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'subjectRef',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
                  offerId: z.string().regex(/^ofr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  subjectRef: z.string(),
                  status: z.enum(['active', 'revoked', 'paused']),
                  channel: z.string().optional(),
                  grantedAt: z.string().datetime({ offset: true }),
                  stopProcessingStatus: z
                    .enum(['not_required', 'in_progress', 'completed', 'stuck'])
                    .optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/consents',
    alias: 'grantConsent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: grantConsent_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            offerId: z.string().regex(/^ofr_[0-9A-HJKMNP-TV-Z]{26}$/),
            subjectRef: z.string(),
            status: z.enum(['active', 'revoked', 'paused']),
            channel: z.string().optional(),
            grantedAt: z.string().datetime({ offset: true }),
            stopProcessingStatus: z
              .enum(['not_required', 'in_progress', 'completed', 'stuck'])
              .optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/consents/:consentId',
    alias: 'getConsent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'consentId',
        type: 'Path',
        schema: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            offerId: z.string().regex(/^ofr_[0-9A-HJKMNP-TV-Z]{26}$/),
            subjectRef: z.string(),
            status: z.enum(['active', 'revoked', 'paused']),
            channel: z.string().optional(),
            grantedAt: z.string().datetime({ offset: true }),
            stopProcessingStatus: z
              .enum(['not_required', 'in_progress', 'completed', 'stuck'])
              .optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/consents/:consentId/revoke',
    alias: 'revokeConsent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z.object({ reason: z.string().min(1) }).passthrough(),
      },
      {
        name: 'consentId',
        type: 'Path',
        schema: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            consentId: z.string().regex(/^cns_[0-9A-HJKMNP-TV-Z]{26}$/),
            revokedAt: z.string().datetime({ offset: true }),
            reason: z.string(),
            stopProcessingStatus: z
              .enum(['not_required', 'in_progress', 'completed', 'stuck'])
              .optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
