/**
 * ExecuteResumeOffersForIncident - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteResumeOffersForIncident Use Case
 *
 * DDD: Application use case for get ResumeOffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ResumeOffersForIncidentInput, ResumeOffersForIncidentOutput } from "../dto/resume-offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { ResumeOfferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteResumeOffersForIncident {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly resumeOffer: ResumeOfferRepository
  ) {}

  async execute(input: ResumeOffersForIncidentInput): Promise<ResumeOffersForIncidentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: confirm
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).incidentId) {
      throw new ValidationError("incidentId is required");
    }
    const incidentId = (input as any).incidentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.resumeOffer.resumeOffersForIncident({ incidentId: incidentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${incidentId}`);
    }

    return entity as ResumeOffersForIncidentOutput;
  }
}
