/**
 * ExecuteDeclareTrustIncident - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeclareTrustIncident Use Case
 *
 * DDD: Application use case for get Incident.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeclareTrustIncidentInput, DeclareTrustIncidentOutput } from "../dto/incident.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { IncidentRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteDeclareTrustIncident {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly incident: IncidentRepository
  ) {}

  async execute(input: DeclareTrustIncidentInput): Promise<DeclareTrustIncidentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: linkedOfferIds, severity, summary
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.incident.declareTrustIncident({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as DeclareTrustIncidentOutput;
  }
}
