/**
 * ArchiveRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArchiveRepository Port
 *
 * DDD: Application port for archiverepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ArchiveJourneyInput, ArchiveJourneyOutput } from "../dto/archive.dto";
export interface ArchiveRepository {
  archiveJourney(input: ArchiveJourneyInput): Promise<ArchiveJourneyOutput>;
}

export type { ArchiveJourneyInput, ArchiveJourneyOutput } from "../dto/archive.dto";
