/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approval-repository.ddb.js";
export * from "./offer-repository.ddb.js";
export * from "./submit-approval-repository.ddb.js";
export * from "./version-repository.ddb.js";
export * from "./approval-repository.adapter.js";
export * from "./offer-repository.adapter.js";
export * from "./submit-approval-repository.adapter.js";
export * from "./version-repository.adapter.js";
