/**
 * SubmitApprovalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitApprovalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubmitApprovalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubmitApprovalRepository,
} from "@offertrail/services/offers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubmitApprovalRepositoryDdb } from "./submit-approval-repository.ddb.js";

/**
 * SubmitApprovalRepositoryAdapter
 *
 * Implements SubmitApprovalRepository port for infrastructure layer.
 */
export class SubmitApprovalRepositoryAdapter implements SubmitApprovalRepository {
  private readonly ddb: SubmitApprovalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubmitApprovalRepositoryDdb(this.dynamoClient);
  }

  async submitOfferForApproval(input: Parameters<SubmitApprovalRepository['submitOfferForApproval']>[0]): Promise<Awaited<ReturnType<SubmitApprovalRepository['submitOfferForApproval']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitOfferForApproval(input);
  }
}
