/**
 * CreateSubmitApproval DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SubmitOfferForApprovalParams } from "@offertrail/core/offers";

export function createCreateSubmitApprovalRequest(overrides: Partial<SubmitOfferForApprovalParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
