/**
 * ArchiveJourney handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { archiveJourney } from "@offertrail/api-server/domains/journeys/handlers";
import type { JourneysDDDDependencies } from "@offertrail/api-server/domains/journeys";
import { createCreateArchiveRequest } from "@offertrail/factories/journeys";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offertrail/tests/shared";
import { JOURNEYS_USE_CASES } from "../__factories__/use-cases.js";

describe("ArchiveJourney", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: JourneysDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<JourneysDDDDependencies>(
      JOURNEYS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateArchiveRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeArchiveJourney, "execute").mockResolvedValue(useCaseResult);

    await archiveJourney(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeArchiveJourney.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
