/**
 * FreezeCollection DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FreezeCollection DTOs
 *
 * DDD: Application DTOs for FreezeCollection use cases.
 */

import type { FreezeOfferCollectionParams, FreezeOfferCollectionRequestInput } from "@offertrail/core/fulfilments/types";

export type FreezeOfferCollectionInput = FreezeOfferCollectionParams & FreezeOfferCollectionRequestInput;

export type FreezeOfferCollectionOutput = {};
