/**
 * Fulfilment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fulfilment DTOs
 *
 * DDD: Application DTOs for Fulfilment use cases.
 */

import type { GetFulfilmentParams, ListFulfilmentsParams, RecordFulfilmentRequestInput } from "@offertrail/core/fulfilments/types";

export type ListFulfilmentsInput = ListFulfilmentsParams;

export type RecordFulfilmentInput = RecordFulfilmentRequestInput;

export type GetFulfilmentInput = GetFulfilmentParams;

export type ListFulfilmentsOutput = {};

export type RecordFulfilmentOutput = {};

export type GetFulfilmentOutput = {};
