/**
 * Retry DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Retry DTOs
 *
 * DDD: Application DTOs for Retry use cases.
 */

import type { RetryFulfilmentParams } from "@offertrail/core/fulfilments/types";

export type RetryFulfilmentInput = RetryFulfilmentParams;

export type RetryFulfilmentOutput = {};
