/**
 * ExecuteListOfferVersions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOfferVersions Use Case
 *
 * DDD: Application use case for list Version.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOfferVersionsInput, ListOfferVersionsOutput } from "../dto/version.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { VersionRepository } from "../ports";

export class ExecuteListOfferVersions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly version: VersionRepository
  ) {}

  async execute(input: ListOfferVersionsInput): Promise<ListOfferVersionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ofrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.version.listOfferVersions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOfferVersionsOutput;
  }
}
