/**
 * ExecuteListOfferApprovals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListOfferApprovals Use Case
 *
 * DDD: Application use case for list Approval.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListOfferApprovalsInput, ListOfferApprovalsOutput } from "../dto/approval.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { ApprovalRepository } from "../ports";

export class ExecuteListOfferApprovals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly approval: ApprovalRepository
  ) {}

  async execute(input: ListOfferApprovalsInput): Promise<ListOfferApprovalsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ofrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.approval.listOfferApprovals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListOfferApprovalsOutput;
  }
}
