/**
 * SubmitApprovalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitApprovalRepository Port
 *
 * DDD: Application port for submitapprovalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitOfferForApprovalInput, SubmitOfferForApprovalOutput } from "../dto/submit-approval.dto";
export interface SubmitApprovalRepository {
  submitOfferForApproval(input: SubmitOfferForApprovalInput): Promise<SubmitOfferForApprovalOutput>;
}

export type { SubmitOfferForApprovalInput, SubmitOfferForApprovalOutput } from "../dto/submit-approval.dto";
