/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as consentsRoutes from "../../domains/consents/routes/index.js";
import * as fulfilmentsRoutes from "../../domains/fulfilments/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as incidentsRoutes from "../../domains/incidents/routes/index.js";
import * as journeysRoutes from "../../domains/journeys/routes/index.js";
import * as offersRoutes from "../../domains/offers/routes/index.js";
import * as reportingRoutes from "../../domains/reporting/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "consents", mod: consentsRoutes },
  { domain: "fulfilments", mod: fulfilmentsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "incidents", mod: incidentsRoutes },
  { domain: "journeys", mod: journeysRoutes },
  { domain: "offers", mod: offersRoutes },
  { domain: "reporting", mod: reportingRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
