/**
 * PauseOffer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseOffer DTOs
 *
 * DDD: Application DTOs for PauseOffer use cases.
 */

import type { PauseOffersForIncidentParams, PauseOffersForIncidentRequestInput } from "@offertrail/core/incidents/types";

export type PauseOffersForIncidentInput = PauseOffersForIncidentParams & PauseOffersForIncidentRequestInput;

export type PauseOffersForIncidentOutput = {};
