/**
 * ResumeOffer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeOffer DTOs
 *
 * DDD: Application DTOs for ResumeOffer use cases.
 */

import type { ResumeOffersForIncidentParams, ResumeOffersForIncidentRequestInput } from "@offertrail/core/incidents/types";

export type ResumeOffersForIncidentInput = ResumeOffersForIncidentParams & ResumeOffersForIncidentRequestInput;

export type ResumeOffersForIncidentOutput = {};
