/**
 * JourneyCompareRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JourneyCompareRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JourneyCompareRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JourneyCompareRepository,
} from "@offertrail/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JourneyCompareRepositoryDdb } from "./journey-compare-repository.ddb.js";

/**
 * JourneyCompareRepositoryAdapter
 *
 * Implements JourneyCompareRepository port for infrastructure layer.
 */
export class JourneyCompareRepositoryAdapter implements JourneyCompareRepository {
  private readonly ddb: JourneyCompareRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JourneyCompareRepositoryDdb(this.dynamoClient);
  }

  async compareJourneys(input: Parameters<JourneyCompareRepository['compareJourneys']>[0]): Promise<Awaited<ReturnType<JourneyCompareRepository['compareJourneys']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.compareJourneys(input);
  }
}
