/**
 * OfferPerformanceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OfferPerformanceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements OfferPerformanceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  OfferPerformanceRepository,
} from "@offertrail/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OfferPerformanceRepositoryDdb } from "./offer-performance-repository.ddb.js";

/**
 * OfferPerformanceRepositoryAdapter
 *
 * Implements OfferPerformanceRepository port for infrastructure layer.
 */
export class OfferPerformanceRepositoryAdapter implements OfferPerformanceRepository {
  private readonly ddb: OfferPerformanceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OfferPerformanceRepositoryDdb(this.dynamoClient);
  }

  async getOfferPerformanceReport(input: Parameters<OfferPerformanceRepository['getOfferPerformanceReport']>[0]): Promise<Awaited<ReturnType<OfferPerformanceRepository['getOfferPerformanceReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getOfferPerformanceReport(input);
  }
}
