/**
 * IncidentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncidentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IncidentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IncidentRepository,
} from "@offertrail/services/incidents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IncidentRepositoryDdb } from "./incident-repository.ddb.js";

/**
 * IncidentRepositoryAdapter
 *
 * Implements IncidentRepository port for infrastructure layer.
 */
export class IncidentRepositoryAdapter implements IncidentRepository {
  private readonly ddb: IncidentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IncidentRepositoryDdb(this.dynamoClient);
  }

  async listTrustIncidents(input: Parameters<IncidentRepository['listTrustIncidents']>[0]): Promise<Awaited<ReturnType<IncidentRepository['listTrustIncidents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTrustIncidents(input);
  }

  async declareTrustIncident(input: Parameters<IncidentRepository['declareTrustIncident']>[0]): Promise<Awaited<ReturnType<IncidentRepository['declareTrustIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.declareTrustIncident(input);
  }

  async getTrustIncident(input: Parameters<IncidentRepository['getTrustIncident']>[0]): Promise<Awaited<ReturnType<IncidentRepository['getTrustIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTrustIncident(input);
  }
}
