/**
 * ResumeOfferRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeOfferRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ResumeOfferRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ResumeOfferRepository,
} from "@offertrail/services/incidents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { OfferRepositoryDdb } from "./offer-repository.ddb.js";

/**
 * ResumeOfferRepositoryAdapter
 *
 * Implements ResumeOfferRepository port for infrastructure layer.
 */
export class ResumeOfferRepositoryAdapter implements ResumeOfferRepository {
  private readonly ddb: OfferRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new OfferRepositoryDdb(this.dynamoClient);
  }

  async resumeOffersForIncident(input: Parameters<ResumeOfferRepository['resumeOffersForIncident']>[0]): Promise<Awaited<ReturnType<ResumeOfferRepository['resumeOffersForIncident']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.resumeOffersForIncident(input);
  }
}
