/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Offers Domain Use Cases
 * 
 * List of all use case names for the offers domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const OFFERS_USE_CASES = [
  "executeCreateOffer",
  "executeGetOffer",
  "executeListOfferApprovals",
  "executeListOfferVersions",
  "executeListOffers",
  "executeListPendingApprovals",
  "executeRecordOfferApproval",
  "executeSubmitOfferForApproval",
  "executeUpdateOffer"
] as const;
