/**
 * AuditStatementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditStatementRepository Port
 *
 * DDD: Application port for auditstatementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAuditStatementInput, GetAuditStatementOutput } from "../dto/audit-statement.dto";
export interface AuditStatementRepository {
  getAuditStatement(input: GetAuditStatementInput): Promise<GetAuditStatementOutput>;
}

export type { GetAuditStatementInput, GetAuditStatementOutput } from "../dto/audit-statement.dto";
