/**
 * Handlers for Archive
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: journeys
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { JourneysDomainModule } from "../dependencies/journeys-ddd.dependencies.js";
import type { ArchiveJourneyInput } from "@offertrail/services/journeys";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/journeys/{journeyId}/archive
 * Operation: archiveJourney
 */
export async function archiveJourney(
  request: FastifyRequest<{ Params: { journeyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: JourneysDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ArchiveJourneyInput = {
    journeyId: request.params.journeyId,
  };
  const result = await deps.useCases.archives.get.execute(input);
  return reply.code(200).send(result);
}


