/**
 * GetFulfilment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetFulfilmentParams } from "@offertrail/core/fulfilments";

export function createGetFulfilmentRequest(overrides: Partial<GetFulfilmentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
