/**
 * ExecuteCompareJourneys - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCompareJourneys Use Case
 *
 * DDD: Application use case for get JourneyCompare.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CompareJourneysInput, CompareJourneysOutput } from "../dto/journey-compare.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { JourneyCompareRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteCompareJourneys {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly journeyCompare: JourneyCompareRepository
  ) {}

  async execute(input: CompareJourneysInput): Promise<CompareJourneysOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.journeyCompare.compareJourneys({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as CompareJourneysOutput;
  }
}
