/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { auditStatementRoutes } from "./audit-statement.routes.js";
export { journeyCompareRoutes } from "./journey-compare.routes.js";
export { offerPerformanceRoutes } from "./offer-performance.routes.js";
