/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditStatementRepositoryAdapter,
  JourneyCompareRepositoryAdapter,
  OfferPerformanceRepositoryAdapter,
} from "@offertrail/adapters/reporting";
import { getIdGeneratorService } from "@offertrail/adapters";
import type { AdapterDynamoDBClient } from "@offertrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCompareJourneys,
  ExecuteGetAuditStatement,
  ExecuteGetOfferPerformanceReport,
} from "@offertrail/services/reporting/usecases";
// Ports (interfaces)
import type {
  AuditStatementRepository,
  JourneyCompareRepository,
  OfferPerformanceRepository,
} from "@offertrail/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    auditStatements: AuditStatementRepository;
    journeyCompares: JourneyCompareRepository;
    offerPerformances: OfferPerformanceRepository;
  };
  useCases: {
    auditStatements: {
      get: ExecuteGetAuditStatement;
    };
    journeyCompares: {
      get: ExecuteCompareJourneys;
    };
    offerPerformances: {
      get: ExecuteGetOfferPerformanceReport;
    };
  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      auditStatements?: AuditStatementRepository;
      journeyCompares?: JourneyCompareRepository;
      offerPerformances?: OfferPerformanceRepository;
    } = {};

    obj.auditStatements = new AuditStatementRepositoryAdapter(dynamoClient);
    obj.journeyCompares = new JourneyCompareRepositoryAdapter(dynamoClient);
    obj.offerPerformances = new OfferPerformanceRepositoryAdapter(dynamoClient);
    return {
      auditStatements: obj.auditStatements!,
      journeyCompares: obj.journeyCompares!,
      offerPerformances: obj.offerPerformances!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    auditStatements: {
      get: new ExecuteGetAuditStatement(executionContext, idGenerator, repos.auditStatements),
    },
    journeyCompares: {
      get: new ExecuteCompareJourneys(executionContext, idGenerator, repos.journeyCompares),
    },
    offerPerformances: {
      get: new ExecuteGetOfferPerformanceReport(executionContext, idGenerator, repos.offerPerformances),
    },
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
