/**
 * Fulfilments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fulfilments Domain Module - Composition root
 *
 * DDD: Composition root for fulfilments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FreezeCollectionRepositoryAdapter,
  FulfilmentRepositoryAdapter,
  RetryRepositoryAdapter,
} from "@offertrail/adapters/fulfilments";
import { getIdGeneratorService } from "@offertrail/adapters";
import type { AdapterDynamoDBClient } from "@offertrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteFreezeOfferCollection,
  ExecuteGetFulfilment,
  ExecuteListFulfilments,
  ExecuteRecordFulfilment,
  ExecuteRetryFulfilment,
} from "@offertrail/services/fulfilments/usecases";
// Ports (interfaces)
import type {
  FreezeCollectionRepository,
  FulfilmentRepository,
  RetryRepository,
} from "@offertrail/services/fulfilments/ports";

export interface FulfilmentsDomainModule {
  repos: {
    freezeCollections: FreezeCollectionRepository;
    fulfilments: FulfilmentRepository;
    retries: RetryRepository;
  };
  useCases: {
    freezeCollections: {
      get: ExecuteFreezeOfferCollection;
    };
    fulfilments: {
      get: ExecuteGetFulfilment;
      list: ExecuteListFulfilments;
    };
    retries: {
      get: ExecuteRetryFulfilment;
    };
  };
}

export function buildFulfilmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FulfilmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      freezeCollections?: FreezeCollectionRepository;
      fulfilments?: FulfilmentRepository;
      retries?: RetryRepository;
    } = {};

    obj.freezeCollections = new FreezeCollectionRepositoryAdapter(dynamoClient);
    obj.fulfilments = new FulfilmentRepositoryAdapter(dynamoClient);
    obj.retries = new RetryRepositoryAdapter(dynamoClient);
    return {
      freezeCollections: obj.freezeCollections!,
      fulfilments: obj.fulfilments!,
      retries: obj.retries!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    freezeCollections: {
      get: new ExecuteFreezeOfferCollection(executionContext, idGenerator, repos.freezeCollections),
    },
    fulfilments: {
      get: new ExecuteGetFulfilment(executionContext, idGenerator, repos.fulfilments),
      list: new ExecuteListFulfilments(executionContext, idGenerator, repos.fulfilments),
    },
    retries: {
      get: new ExecuteRetryFulfilment(executionContext, idGenerator, repos.retries),
    },
  };
  return { repos, useCases: useCases as FulfilmentsDomainModule["useCases"] };
}
