/**
 * FulfilmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FulfilmentRepository Port
 *
 * DDD: Application port for fulfilmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetFulfilmentInput, GetFulfilmentOutput, ListFulfilmentsInput, ListFulfilmentsOutput, RecordFulfilmentInput, RecordFulfilmentOutput } from "../dto/fulfilment.dto";
export interface FulfilmentRepository {
  listFulfilments(input: ListFulfilmentsInput): Promise<ListFulfilmentsOutput>;
  recordFulfilment(input: RecordFulfilmentInput): Promise<RecordFulfilmentOutput>;
  getFulfilment(input: GetFulfilmentInput): Promise<GetFulfilmentOutput>;
}

export type { GetFulfilmentInput, GetFulfilmentOutput, ListFulfilmentsInput, ListFulfilmentsOutput, RecordFulfilmentInput, RecordFulfilmentOutput } from "../dto/fulfilment.dto";
