/**
 * ResumeOfferRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResumeOfferRepository Port
 *
 * DDD: Application port for resumeofferrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ResumeOffersForIncidentInput, ResumeOffersForIncidentOutput } from "../dto/resume-offer.dto";
export interface ResumeOfferRepository {
  resumeOffersForIncident(input: ResumeOffersForIncidentInput): Promise<ResumeOffersForIncidentOutput>;
}

export type { ResumeOffersForIncidentInput, ResumeOffersForIncidentOutput } from "../dto/resume-offer.dto";
