/**
 * Handlers for FreezeCollection
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentsDomainModule } from "../dependencies/fulfilments-ddd.dependencies.js";
import type { FreezeOfferCollectionInput } from "@offertrail/services/fulfilments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/offers/{offerId}/freeze-collection
 * Operation: freezeOfferCollection
 */
export async function freezeOfferCollection(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: FreezeOfferCollectionInput = {
    offerId: request.params.offerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.freezeCollections.get.execute(input);
  return reply.code(200).send(result);
}


