/**
 * Handlers for Fulfilment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentsDomainModule } from "../dependencies/fulfilments-ddd.dependencies.js";
import type { GetFulfilmentInput, ListFulfilmentsInput, RecordFulfilmentInput } from "@offertrail/services/fulfilments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/fulfilments
 * Operation: listFulfilments
 */
export async function listFulfilments(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], offerId?: string | string[], consentId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListFulfilmentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.fulfilments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/fulfilments
 * Operation: recordFulfilment
 */
export async function recordFulfilment(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: FulfilmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordFulfilmentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.fulfilments.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/fulfilments/{fulfilmentId}
 * Operation: getFulfilment
 */
export async function getFulfilment(
  request: FastifyRequest<{ Params: { fulfilmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetFulfilmentInput = {
    fulfilmentId: request.params.fulfilmentId,
  };
  const result = await deps.useCases.fulfilments.get.execute(input);
  return reply.code(200).send(result);
}


