/**
 * Handlers for Retry
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FulfilmentsDomainModule } from "../dependencies/fulfilments-ddd.dependencies.js";
import type { RetryFulfilmentInput } from "@offertrail/services/fulfilments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/fulfilments/{fulfilmentId}/retry
 * Operation: retryFulfilment
 */
export async function retryFulfilment(
  request: FastifyRequest<{ Params: { fulfilmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FulfilmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RetryFulfilmentInput = {
    fulfilmentId: request.params.fulfilmentId,
  };
  const result = await deps.useCases.retries.get.execute(input);
  return reply.code(200).send(result);
}


