/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { freezeCollectionRoutes } from "./freeze-collection.routes.js";
export { fulfilmentRoutes } from "./fulfilment.routes.js";
export { retryRoutes } from "./retry.routes.js";
