/**
 * GetFulfilment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFulfilment } from "@offertrail/api-server/domains/fulfilments/handlers";
import type { FulfilmentsDDDDependencies } from "@offertrail/api-server/domains/fulfilments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offertrail/tests/shared";
import { FULFILMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFulfilment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FulfilmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FulfilmentsDDDDependencies>(
      FULFILMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFulfilment, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { fulfilmentId: entity.id };

    await getFulfilment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFulfilment.execute).toHaveBeenCalledWith(expect.objectContaining({ fulfilmentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { fulfilmentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFulfilment, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFulfilment(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
