/**
 * RecordFulfilment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordFulfilment } from "@offertrail/api-server/domains/fulfilments/handlers";
import type { FulfilmentsDDDDependencies } from "@offertrail/api-server/domains/fulfilments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offertrail/tests/shared";
import { FULFILMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordFulfilment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FulfilmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FulfilmentsDDDDependencies>(
      FULFILMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordFulfilment, "execute").mockResolvedValue(useCaseResult);

    await recordFulfilment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordFulfilment.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
