/**
 * Offers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Offers Domain Module - Composition root
 *
 * DDD: Composition root for offers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApprovalRepositoryAdapter,
  OfferRepositoryAdapter,
  SubmitApprovalRepositoryAdapter,
  VersionRepositoryAdapter,
} from "@offertrail/adapters/offers";
import { getIdGeneratorService } from "@offertrail/adapters";
import type { AdapterDynamoDBClient } from "@offertrail/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateOffer,
  ExecuteGetOffer,
  ExecuteListOfferApprovals,
  ExecuteListOfferVersions,
  ExecuteListOffers,
  ExecuteListPendingApprovals,
  ExecuteRecordOfferApproval,
  ExecuteSubmitOfferForApproval,
  ExecuteUpdateOffer,
} from "@offertrail/services/offers/usecases";
// Ports (interfaces)
import type {
  ApprovalRepository,
  OfferRepository,
  SubmitApprovalRepository,
  VersionRepository,
} from "@offertrail/services/offers/ports";

export interface OffersDomainModule {
  repos: {
    approvals: ApprovalRepository;
    offers: OfferRepository;
    submitApprovals: SubmitApprovalRepository;
    versions: VersionRepository;
  };
  useCases: {
    approvals: {
      get: ExecuteRecordOfferApproval;
      list: ExecuteListOfferApprovals;
    };
    offers: {
      create: ExecuteCreateOffer;
      get: ExecuteGetOffer;
      list: ExecuteListOffers;
      update: ExecuteUpdateOffer;
    };
    submitApprovals: {
      create: ExecuteSubmitOfferForApproval;
    };
    versions: {
      list: ExecuteListOfferVersions;
    };
  };
}

export function buildOffersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OffersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approvals?: ApprovalRepository;
      offers?: OfferRepository;
      submitApprovals?: SubmitApprovalRepository;
      versions?: VersionRepository;
    } = {};

    obj.approvals = new ApprovalRepositoryAdapter(dynamoClient);
    obj.offers = new OfferRepositoryAdapter(dynamoClient);
    obj.submitApprovals = new SubmitApprovalRepositoryAdapter(dynamoClient);
    obj.versions = new VersionRepositoryAdapter(dynamoClient);
    return {
      approvals: obj.approvals!,
      offers: obj.offers!,
      submitApprovals: obj.submitApprovals!,
      versions: obj.versions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approvals: {
      get: new ExecuteRecordOfferApproval(executionContext, idGenerator, repos.approvals),
      list: new ExecuteListOfferApprovals(executionContext, idGenerator, repos.approvals),
    },
    offers: {
      create: new ExecuteCreateOffer(executionContext, idGenerator, repos.offers),
      get: new ExecuteGetOffer(executionContext, idGenerator, repos.offers),
      list: new ExecuteListOffers(executionContext, idGenerator, repos.offers),
      update: new ExecuteUpdateOffer(executionContext, idGenerator, repos.offers),
    },
    submitApprovals: {
      create: new ExecuteSubmitOfferForApproval(executionContext, idGenerator, repos.submitApprovals),
    },
    versions: {
      list: new ExecuteListOfferVersions(executionContext, idGenerator, repos.versions),
    },
  };
  return { repos, useCases: useCases as OffersDomainModule["useCases"] };
}
