/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Fulfilments Domain Use Cases
 * 
 * List of all use case names for the fulfilments domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const FULFILMENTS_USE_CASES = [
  "executeFreezeOfferCollection",
  "executeGetFulfilment",
  "executeListFulfilments",
  "executeRecordFulfilment",
  "executeRetryFulfilment"
] as const;
