/**
 * GrantConsent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { grantConsent } from "@offertrail/api-server/domains/consents/handlers";
import type { ConsentsDDDDependencies } from "@offertrail/api-server/domains/consents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@offertrail/tests/shared";
import { CONSENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GrantConsent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConsentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConsentsDDDDependencies>(
      CONSENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeGrantConsent, "execute").mockResolvedValue(useCaseResult);

    await grantConsent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGrantConsent.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
