/**
 * Handlers for Offer
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { OffersDomainModule } from "../dependencies/offers-ddd.dependencies.js";
import type { CreateOfferInput, GetOfferInput, ListOffersInput, UpdateOfferInput } from "@offertrail/services/offers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/offers
 * Operation: listOffers
 */
export async function listOffers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], journeyId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: OffersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListOffersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.offers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/offers
 * Operation: createOffer
 */
export async function createOffer(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: OffersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateOfferInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.offers.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/offers/{offerId}
 * Operation: getOffer
 */
export async function getOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OffersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOfferInput = {
    offerId: request.params.offerId,
  };
  const result = await deps.useCases.offers.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/offers/{offerId}
 * Operation: updateOffer
 */
export async function updateOffer(
  request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: OffersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateOfferInput = {
    offerId: request.params.offerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.offers.update.execute(input);
  return reply.code(200).send(result);
}


