/**
 * ExecuteRetryFulfilment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRetryFulfilment Use Case
 *
 * DDD: Application use case for get Retry.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RetryFulfilmentInput, RetryFulfilmentOutput } from "../dto/retry.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { RetryRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRetryFulfilment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly retry: RetryRepository
  ) {}

  async execute(input: RetryFulfilmentInput): Promise<RetryFulfilmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fulId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).fulfilmentId) {
      throw new ValidationError("fulfilmentId is required");
    }
    const fulfilmentId = (input as any).fulfilmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.retry.retryFulfilment({ fulfilmentId: fulfilmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${fulfilmentId}`);
    }

    return entity as RetryFulfilmentOutput;
  }
}
