/**
 * ExecuteFreezeOfferCollection - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFreezeOfferCollection Use Case
 *
 * DDD: Application use case for get FreezeCollection.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FreezeOfferCollectionInput, FreezeOfferCollectionOutput } from "../dto/freeze-collection.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { FreezeCollectionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFreezeOfferCollection {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly freezeCollection: FreezeCollectionRepository
  ) {}

  async execute(input: FreezeOfferCollectionInput): Promise<FreezeOfferCollectionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fulId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).offerId) {
      throw new ValidationError("offerId is required");
    }
    const offerId = (input as any).offerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.freezeCollection.freezeOfferCollection({ offerId: offerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${offerId}`);
    }

    return entity as FreezeOfferCollectionOutput;
  }
}
