/**
 * ExecuteRecordFulfilment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordFulfilment Use Case
 *
 * DDD: Application use case for get Fulfilment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordFulfilmentInput, RecordFulfilmentOutput } from "../dto/fulfilment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { FulfilmentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordFulfilment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fulfilment: FulfilmentRepository
  ) {}

  async execute(input: RecordFulfilmentInput): Promise<RecordFulfilmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fulId();

    // All field names extracted from OpenAPI spec: consentId, evidenceRef, fulfilledAt, fulfilmentType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).consentId) {
      throw new ValidationError("consentId is required");
    }
    const consentId = (input as any).consentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.fulfilment.recordFulfilment({ consentId: consentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${consentId}`);
    }

    return entity as RecordFulfilmentOutput;
  }
}
