/**
 * ExecuteListFulfilments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFulfilments Use Case
 *
 * DDD: Application use case for list Fulfilment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFulfilmentsInput, ListFulfilmentsOutput } from "../dto/fulfilment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@offertrail/services/_shared/index.js";
import type { FulfilmentRepository } from "../ports";

export class ExecuteListFulfilments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fulfilment: FulfilmentRepository
  ) {}

  async execute(input: ListFulfilmentsInput): Promise<ListFulfilmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fulId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.fulfilment.listFulfilments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFulfilmentsOutput;
  }
}
