/**
 * Approval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Approval DTOs
 *
 * DDD: Application DTOs for Approval use cases.
 */

import type { ListOfferApprovalsParams, ListPendingApprovalsParams, RecordOfferApprovalParams, RecordOfferApprovalRequestInput } from "@offertrail/core/offers/types";

export type RecordOfferApprovalInput = RecordOfferApprovalParams & RecordOfferApprovalRequestInput;

export type ListPendingApprovalsInput = ListPendingApprovalsParams;

export type ListOfferApprovalsInput = ListOfferApprovalsParams;

export type RecordOfferApprovalOutput = {};

export type ListPendingApprovalsOutput = {};

export type ListOfferApprovalsOutput = {};
