/**
 * SubmitApproval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitApproval DTOs
 *
 * DDD: Application DTOs for SubmitApproval use cases.
 */

import type { SubmitOfferForApprovalParams } from "@offertrail/core/offers/types";

export type SubmitOfferForApprovalInput = SubmitOfferForApprovalParams;

export type SubmitOfferForApprovalOutput = {};
