/**
 * Version DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Version DTOs
 *
 * DDD: Application DTOs for Version use cases.
 */

import type { ListOfferVersionsParams } from "@offertrail/core/offers/types";

export type ListOfferVersionsInput = ListOfferVersionsParams;

export type ListOfferVersionsOutput = {};
