/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fulfilments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./freeze-collection-repository.ddb.js";
export * from "./fulfilment-repository.ddb.js";
export * from "./retry-repository.ddb.js";
export * from "./freeze-collection-repository.adapter.js";
export * from "./fulfilment-repository.adapter.js";
export * from "./retry-repository.adapter.js";
