/**
 * Routes for Approval
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: offers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listOfferApprovals, listPendingApprovals, recordOfferApproval } from "../handlers/approval.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function approvalRoutes(fastify: FastifyInstance) {
  // GET /v1/approvals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/approvals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOffersDependenciesForRequest();
        await listPendingApprovals(request, reply, deps);
      });
    }
  );


  // POST /v1/offers/{offerId}/approval (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/offers/:offerId/approval",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOffersDependenciesForRequest();
        await recordOfferApproval(request, reply, deps);
      });
    }
  );


  // GET /v1/offers/{offerId}/approvals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/offers/:offerId/approvals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { offerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOffersDependenciesForRequest();
        await listOfferApprovals(request, reply, deps);
      });
    }
  );


}
